[package]
name = "Vector_Calculator"
version = "0.1.0"
authors = ["Cole"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_input = "0.8.3"